services:
  - type: web
    name: movie-web-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
      - key: WASABI_ACCESS_KEY_ID
        sync: false
      - key: WASABI_SECRET_ACCESS_KEY
        sync: false
      - key: WASABI_BUCKET_NAME
        sync: false
      - key: WASABI_REGION
        value: us-east-1
      - key: WASABI_ENDPOINT
        value: https://s3.us-east-1.wasabisys.com 